import SocketClient from "@/config/SocketClient";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import QueryProvider from "@/config/QueryProvider";

export const metadata = {
  title: {
    template: '%s | Trek-It',
    default: "Trek-It"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body className={` antialiased bg-background  `}>
        <ThemeProvider
          attribute="data-theme"
          defaultTheme="system"
          enableSystem
        >
          <QueryProvider>
            <SocketClient />
            {children}
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}