"use client";

import { useRouter } from "next/navigation";
import { motion, AnimatePresence } from "motion/react";
import { MessageSquareText, CalendarX, Check, X, Users } from "lucide-react";

import { Button } from "@/components/ui/Button";
import MiniCard from "@/components/ui/MiniCard";
import Badge from "@/components/ui/Badge";
import useChatStore from "@/store/chat/chat.store";
import { showToast } from "@/store/ui.store";
import {
    useGetMyCustomRequests,
    useAcceptCustomRequest,
    useRejectCustomRequest,
} from "@/queries/customRequest.query";

// ---------------------------------------------------------------------------

const STATUS_BADGE_MAP = {
    pending:  { label: "Pending",  color: "yellow" },
    accepted: { label: "Accepted", color: "green"  },
    rejected: { label: "Rejected", color: "red"    },
};

function EmptyState() {
    return (
        <motion.div
            key="empty"
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="flex flex-col items-center justify-center py-16 text-text/50"
        >
            <CalendarX size={36} className="mb-3 opacity-30" />
            <p className="text-sm">No customization requests yet</p>
        </motion.div>
    );
}

function Skeleton() {
    return (
        <div className="border border-secondary rounded-lg p-4 flex flex-col gap-3 animate-pulse">
            <div className="h-4 w-32 bg-secondary/40 rounded" />
            <div className="h-10 w-full bg-secondary/20 rounded" />
            <div className="h-3 w-48 bg-secondary/20 rounded" />
        </div>
    );
}

function CustomRequestCard({ request }) {
    const router = useRouter();
    const openDirectChat = useChatStore((s) => s.openDirectChat);

    const handleAccepted = async (tourist) => {
        if (!tourist) return;
        try {
            await openDirectChat(tourist, () => router.push("/chat"));
            showToast({
                title: "Request accepted",
                message: `Opening chat with ${tourist?.name}…`,
            });
        } catch {
            // Chat opened fine on backend even if redirect fails
            router.push("/chat");
        }
    };

    const acceptRequest = useAcceptCustomRequest(handleAccepted);
    const rejectRequest = useRejectCustomRequest();

    const isPending = request?.status?.toLowerCase().trim() === "pending";
    const statusBadge = STATUS_BADGE_MAP[request?.status?.toLowerCase().trim()] ?? STATUS_BADGE_MAP.pending;

    // Parse group size and price from the description generated by the service
    // e.g. `Tourist requests "..." for a group of 5. Quoted price: NRS 12,000.`
    const groupSizeMatch = request?.description?.match(/group of (\d+)/);
    const priceMatch     = request?.description?.match(/NRS ([\d,]+)/);
    const groupSize      = groupSizeMatch?.[1] ?? null;
    const totalPrice     = priceMatch?.[1]     ?? null;

    return (
        <motion.article
            layout
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -6 }}
            transition={{ duration: 0.18 }}
            className="border border-secondary rounded-lg overflow-hidden"
        >
            {/* Header strip */}
            <div className="flex items-center justify-between px-4 py-2 bg-secondary/20 border-b border-secondary">
                <span className="text-xs text-text/50 uppercase tracking-wide flex items-center gap-1.5">
                    <MessageSquareText size={12} />
                    Package Customization Request
                </span>
                <Badge color={statusBadge.color}>{statusBadge.label}</Badge>
            </div>

            {/* Tourist info */}
            <div className="px-4 pt-3">
                <MiniCard
                    person={request?.tourist}
                    subtitle="Tourist"
                    options={{ border: false, star: false }}
                />
            </div>

            {/* Group size + quoted price */}
            {(groupSize || totalPrice) && (
                <div className="px-4 pt-2 flex items-center gap-4 text-xs text-text/60">
                    {groupSize && (
                        <span className="flex items-center gap-1">
                            <Users size={11} />
                            {groupSize} {groupSize === "1" ? "person" : "people"}
                        </span>
                    )}
                    {totalPrice && (
                        <span>Quoted: NRS {totalPrice}</span>
                    )}
                </div>
            )}

            {/* Tourist's optional message */}
            {request?.description && (
                <p className="mx-4 mt-2 text-sm text-text/60 px-3 py-2 border-l-2 border-secondary rounded-sm bg-secondary/10 leading-relaxed">
                    {request.description}
                </p>
            )}

            {/* Accept / Reject */}
            <div className="px-4 py-3 mt-1 border-t border-secondary flex gap-3">
                <Button
                    variant="outline"
                    color="green"
                    size="sm"
                    className="flex-1"
                    onClick={() => acceptRequest.mutate(request._id)}
                >
                    <Check size={14} />
                    {acceptRequest.isPending ? "Accepting…" : "Accept"}
                </Button>
                <Button
                    variant="outline"
                    color="red"
                    size="sm"
                    className="flex-1"
                    onClick={() => rejectRequest.mutate(request._id)}
                >
                    <X size={14} />
                    {rejectRequest.isPending ? "Rejecting…" : "Reject"}
                </Button>
            </div>
        </motion.article>
    );
}

// ---------------------------------------------------------------------------

export default function CustomRequests() {
    const { data, isLoading } = useGetMyCustomRequests();
    const requests = data?.docs ?? [];
    const pendingCount = requests.filter((r) => r?.status?.toLowerCase().trim() === "pending").length;

    return (
        <section id="custom-requests" className="flex flex-col gap-5">
            <div className="flex items-center gap-3">
                <MessageSquareText size={20} className="text-primary" />
                <h2 className="text-xl text-primary font-semibold">
                    Customization Requests
                    {pendingCount > 0 && (
                        <span className="ml-2 text-sm font-normal text-text/50">
                            ({pendingCount} pending)
                        </span>
                    )}
                </h2>
            </div>

            {isLoading ? (
                <div className="flex flex-col gap-2.5">
                    <Skeleton />
                    <Skeleton />
                </div>
            ) : (
                <AnimatePresence mode="popLayout">
                    {requests.length === 0 ? (
                        <EmptyState key="empty" />
                    ) : (
                        <motion.div
                            key="list"
                            initial={{ opacity: 0, y: 6 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0 }}
                            transition={{ duration: 0.18, ease: "easeOut" }}
                            className="flex flex-col gap-2.5"
                        >
                            {requests.map((request) => (
                                <CustomRequestCard key={request._id} request={request} />
                            ))}
                        </motion.div>
                    )}
                </AnimatePresence>
            )}
        </section>
    );
}
